### ISSUE TITLE
Mechanism for enabling community to include wrapped assets in addition to those provided by wrapped.com

### ISSUE THREAD

**Issue by wbnns** [tokensoft/wrapped-tokenlist#4]
Currently the JSON is for wrapped.com assets. Would be nice if there was a way for the community to include other wrapped assets as well.

**Comment by wbnns** [comment]
Related: #2, #3

**Comment by svanas** [comment]
> Currently the JSON is for wrapped.com assets. Would be nice if there was a way for the community to include other wrapped assets as well.

Oh? The "Wrapped Tokens" list should make that more clear then. It should be named "wrapped.com assets" maybe.

**Comment by svanas** [comment]
@wbnns Other than open another PR, what can I do to include other wrapped assets? WUTN is a community-driven project (not a scam) and as such it deserves to be included with a wrapped token list.

**Comment by wbnns** [comment]
@svanas 

> @wbnns Other than open another PR, what can I do to include other wrapped assets? WUTN is a community-driven project (not a scam) and as such it deserves to be included with a wrapped token list.

Understood! For now, just stand by. We'll keep this in mind here as we continue to expand.

**Comment by masonicGIT** [comment]
Let's add them all!

**Comment by svanas** [comment]
@masonicGIT can I open a new PR? I would be happy to help you maintain and gatekeep the list for you if you want.

**Comment by wbnns** [comment]
@svanas

Thanks a bunch for getting the ball rolling on this -- that would be awesome. Let's do it! 👍 

Would you like me to reopen your previous PR or would you like to make a new one? Also, yes, that would be great if you'd like to help maintain and gatekeep the list. Any others besides WUTN that you'd recommend adding?

**Comment by svanas** [comment]
> Would you like me to reopen your previous PR or would you like to make a new one?

@wbnns I will open a new PR. No problem.

**Comment by svanas** [comment]
@wbnns Here is the new PR that I promised I would open: https://github.com/tokensoft/wrapped-tokenlist/pull/7
