### ISSUE TITLE
USDT and USDC are not wrapped tokens

### ISSUE THREAD

**Issue by svanas** [tokensoft/wrapped-tokenlist#8]
I am curious why [USDT](0xdac17f958d2ee523a2206206994597c13d831ec7) and [USDC](0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48) are included with the list. Those are not wrapped tokens. I suggest we limit the list to tokens that truly wrap another token, not include every stablecoin that happens to be pegged to fiat currency.

**Comment by masonicGIT** [comment]
These need to be in the list because investors will want a stablecoin trade pair. If we remove these, investors will only be able to do eth denominated pairs.
